Websocket youtube
VictoriaLabs/bot-youtube pull request #2
Opened 2023-12-13 11:03 UTC by vardose

J'ai créer un websocket pour youtube qui peut envoyer les chats d'un live a un server, il nécéssite une amélioration mais il est disponible pour des tests. Je vais faire la documentation si il est accepté tel quel.

2023-12-13 11:26 UTC, KAymeric requested changes

2023-12-13 11:26 UTC, KAymeric commented on src/index.html
supprime

2023-12-13 11:26 UTC, KAymeric commented on src/dist/app.js
mettre le dist dans le .gitignore

2023-12-20 10:21 UTC, MazBazDev commented on src/app.ts
>  const port = 8000;
le port doit aller dans le .env

Gpt, pourquoi utiliser un .env.exemple ? 
Gpt : 
" Il est crucial de ne pas push le fichier .env contenant des informations sensibles, telles que des clés d'API ou des identifiants de base de données, dans un système de contrôle de version. En revanche, le fichier .env.example peut être push, car il ne contient que des valeurs d'exemple et sert de référence pour la configuration. Veillez à ajouter le fichier .env à la liste des fichiers ignorés par le système de contrôle de version pour garantir la sécurité des informations sensibles." 😎

2023-12-20 10:44 UTC, MazBazDev reviewed
En attente

2024-01-14 14:26 UTC, KAymeric commented on src/socket.js
> +const socket = require('socket.io-client')('http://localhost:4000');
mettre l'url du serveur websocket dans un .env

2024-01-14 14:28 UTC, KAymeric requested changes
Passer le code sous TypeScript
faire une arborescence pour les fichiers

2024-01-14 18:05 UTC, LoanF requested changes

2024-01-14 18:05 UTC, LoanF commented on src/app.js
> +const socket = require('./socket.js');
Pourquoi tu importe socket.js si tu l'utilise pas ?

2024-01-17 12:46 UTC, MazBazDev approved these changes

2024-01-17 12:48 UTC, KAymeric commented on src/app.ts
> +let arr: string[] = ["UCHoLuRQVGaz5lkdnIZWB8Pw","UCrG8mytOLrC_t5vu7To4ajA"]
Met un p'tit com pour dire c'est quoi ces trucs obscurs

2024-01-17 12:49 UTC, KAymeric requested changes

2024-01-17 12:49 UTC, KAymeric commented on src/app.ts
> +let arr: string[] = ["UCHoLuRQVGaz5lkdnIZWB8Pw","UCrG8mytOLrC_t5vu7To4ajA"]
Met un com pour dire à quoi ça sert

2024-01-17 14:59 UTC, KAymeric approved these changes

2024-01-18 08:55 UTC, LoanF approved these changes

2024-01-18 08:56 UTC, merged